# Port of the RightFax Java API
# Author: Ron Smith, ThatAintWorking.com
# Date: 12/7/2011

CONTENT_MIME = 1
CONTENT_TEXT = 2

AVT_SUBMIT = 1
AVT_QUERY = 2
AVT_ACTION = 3

ENCODING_NONE = 0
ENCODING_BASE64 = 1

MIME_BOUNDRY_START  = '----MIMEBOUNDRY\r\n'
MIME_BOUNDRY_ATTACH = '--MIMEBOUNDRY\r\n'
MIME_BOUNDRY_END    = '--MIMEBOUNDRY--\r\n'
